import { useEffect, useState } from 'react';
import { AlertTriangle, Activity, CircleDollarSign, Radio, RefreshCw, Users } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || 'http://localhost:4000/api';
const sample = { streams: [{ title: 'Midnight Mechanics', status: 'live', viewers: 1842, health: 'Healthy' }, { title: 'The Long Table', status: 'live', viewers: 928, health: 'Healthy' }, { title: 'Signal / Noise', status: 'live', viewers: 611, health: 'Healthy' }], alerts: [], anomalies: 0 };

export default function MonitoringDashboard() {
  const [snapshot, setSnapshot] = useState(sample);
  const [status, setStatus] = useState('sample');
  const load = () => { const token = window.localStorage.getItem('vexoryl_token'); setStatus('loading'); fetch(`${API}/admin/monitoring`, { headers: { Authorization: `Bearer ${token}` } }).then(async (response) => { if (!response.ok) throw new Error('Monitoring unavailable'); setSnapshot(await response.json()); setStatus('live'); }).catch(() => setStatus('sample')); };
  useEffect(() => { load(); const interval = window.setInterval(load, 30000); return () => window.clearInterval(interval); }, []);
  const totalViewers = snapshot.streams.reduce((sum, stream) => sum + Number(stream.viewers || 0), 0);
  return <section className="monitoring-content"><div className="workspace-heading"><div><p className="eyebrow">Operations control</p><h1>Keep the live floor healthy.</h1><p>Stream health, moderation signals, and payout risk in one quiet view.</p></div><button className="icon-action" onClick={load} title="Refresh monitoring"><RefreshCw size={16} /></button></div><div className="monitoring-status"><span className="status-dot" /> {status === 'live' ? 'Live telemetry' : status === 'loading' ? 'Refreshing telemetry' : 'Sample telemetry'} <small>Updates every 30 seconds</small></div><div className="monitor-metrics"><div><Activity size={18} /><small>Stream health</small><strong>{snapshot.streams.filter((stream) => stream.health === 'Healthy').length}/{snapshot.streams.length} healthy</strong></div><div><Users size={18} /><small>Viewers now</small><strong>{totalViewers.toLocaleString()}</strong></div><div><AlertTriangle size={18} /><small>Moderation alerts</small><strong>{snapshot.alerts.length}</strong></div><div><CircleDollarSign size={18} /><small>Wallet anomalies</small><strong>{snapshot.anomalies}</strong></div></div><div className="monitor-grid"><div className="monitor-panel"><div className="panel-title"><h2>Active streams</h2><span>Provider: Mux</span></div>{snapshot.streams.map((stream) => <div className="stream-health-row" key={stream.title}><span className="health-icon"><Radio size={15} /></span><span><strong>{stream.title}</strong><small>{stream.status} · {Number(stream.viewers).toLocaleString()} viewers</small></span><b className="health-badge">{stream.health}</b></div>)}</div><div className="monitor-panel"><div className="panel-title"><h2>Alert queue</h2><span>{snapshot.alerts.length ? 'Needs review' : 'All clear'}</span></div>{snapshot.alerts.length ? snapshot.alerts.map((alert, index) => <p className="alert-row" key={alert.id || index}><AlertTriangle size={15} /> {alert.reason || alert.type}</p>) : <div className="empty-state"><Activity size={18} /><p>No active moderation or transaction alerts.</p></div>}</div></div></section>;
}
