import { Router } from 'express';
import { login, signup } from '../controllers/authController.js';
import { requireAdmin, requireAuth } from '../middleware/auth.js';
import { analytics, browse, chat, connect, create, createLiveStream, createTaskBid, detail, engage, listTaskBids, monitoring, transition, wallet } from '../controllers/streamController.js';
import { payout } from '../controllers/monetizationController.js';
import { triggerDirectorEvent } from '../controllers/directorController.js';
import { gift } from '../controllers/giftController.js';
import { moderateTextInput } from '../middleware/moderation.js';
import { requirePayoutEligibility } from '../middleware/governance.js';

const router = Router();
router.post('/auth/signup', signup);
router.post('/auth/login', login);
router.get('/streams', browse);
router.get('/streams/:id', detail);
router.post('/streams', requireAuth, create);
router.post('/streams/live', requireAuth, createLiveStream);
router.post('/streams/:id/:action(start|stop)', requireAuth, transition);
router.post('/streams/:id/connect', connect);
router.post('/streams/:id/chat', moderateTextInput, chat);
router.get('/streams/:id/task-bids', requireAuth, listTaskBids);
router.post('/streams/:id/task-bids', requireAuth, createTaskBid);
router.post('/streams/:id/:type(reactions|polls|moderation)', requireAuth, engage);
router.post('/wallet/:type(deposit|withdraw|payout)', requireAuth, wallet);
router.post('/monetization/payout', requireAuth, requirePayoutEligibility, payout);
router.post('/monetization/gift', requireAuth, gift);
router.post('/streams/:id/director/triggers', requireAuth, triggerDirectorEvent);
router.get('/analytics/overview', requireAuth, analytics);
router.get('/admin/monitoring', requireAuth, requireAdmin, monitoring);
export default router;
